"""Plain-Python output files: what `byname show`, Alt+C and output-on-save write.

    # pyn output of f.pyn (generated by byname: edit the .pyn, not this file)
    <record header>
    # ---- f.pyn ----
    <the .pyn, translated>
"""

import ast
from pathlib import Path

from .transform import to_python


def drop_main(code: str) -> str:
    """Remove top-level `if __name__ == "__main__":` blocks, e.g. before pasting into a judge."""
    lines = code.splitlines(keepends=True)
    for node in reversed(ast.parse(code).body):
        t = node.test if isinstance(node, ast.If) else None
        if (
            isinstance(t, ast.Compare)
            and isinstance(t.left, ast.Name)
            and t.left.id == "__name__"
            and isinstance(t.comparators[0], ast.Constant)
            and t.comparators[0].value == "__main__"
        ):
            del lines[node.lineno - 1 : node.end_lineno]
    return "".join(lines).rstrip() + "\n"


def render(src: str, path: Path, strip_main: bool = False) -> str:
    code = to_python(src, str(path), divider=f"# ---- {path.name} ----")
    if strip_main:
        code = drop_main(code)
    return f"# pyn output of {path.name} (generated by byname: edit the .pyn, not this file)\n" + code


def output_path(path: Path) -> Path:
    """python_main.pyn -> python_main.pyn.py, right next to it."""
    return path.with_name(path.name + ".py")
